# All requests containing a cookie should only be used between the front-end and back-end.
# These requests are still documented here to help understand the application.

### Create template
POST http://localhost:8080/template
Cookie: PHPSESSID=cookieValue
Content-Type: application/json

{
	"name": "required",
	"captcha_key": "",
	"email_to": "required",
	"email_replyTo": "",
	"email_cc": "",
	"email_bcc": "",
	"email_fromName": "",
	"email_subject": "required",
	"email_content": "required"
}

### Update template by id
PUT http://localhost:8080/template/:id
Cookie: PHPSESSID=cookieValue
Content-Type: application/json

{
	"name": "required",
	"captcha_key": "",
	"email_to": "required",
	"email_replyTo": "",
	"email_cc": "",
	"email_bcc": "",
	"email_fromName": "",
	"email_subject": "required",
	"email_content": "required"
}

### Delete template by id
DELETE http://localhost:8080/template/:id
Cookie: PHPSESSID=cookieValue

### Create template access_token
POST http://localhost:8080/template/:id/key
Cookie: PHPSESSID=cookieValue
Content-Type: application/json

{
	"allowed_origin": "https://example.com"
}

### Revoke all template access_tokens
DELETE http://localhost:8080/template/:id/key
Cookie: PHPSESSID=cookieValue

### Submit form by json
POST http://localhost:8080/submit
Authorization: Bearer access_token
Content-Type: application/json

{
	"foo": "Bar"
}
