#!/usr/bin/env php
<?php

require_once __DIR__ . '/../../vendor/autoload.php';

use CQ\Config\Config;
use CQ\JWT\Utils;

$config = new Config(__DIR__ . '/../../bootstrap');
$config->attach('jwt');

$key = Utils::generateKeys();
$path =  __DIR__ . '/../../.env';

echo PHP_EOL;

if (!file_exists($path)) {
    echo "JWT keypair not set successfully. (bit size: 2048)" . PHP_EOL;
    echo '.env file not found. Please set keys manually.' . PHP_EOL;

    echo PHP_EOL;

    echo 'Private key: ' . PHP_EOL;
    echo $key['privatekey'] . PHP_EOL;

    echo PHP_EOL;

    echo 'Public key: ' . PHP_EOL;
    echo $key['publickey'] . PHP_EOL;

    exit;
}

echo "JWT keypair set successfully. (bit size: 2048)";

file_put_contents($path, str_replace(
    'JWT_PRIVATE_KEY="' . Config::get('jwt.private_key') . '"',
    'JWT_PRIVATE_KEY="' . str_replace(["\r", "\n"], '||', $key['privatekey']) . '"',
    file_get_contents($path)
));

file_put_contents($path, str_replace(
    'JWT_PUBLIC_KEY="' . Config::get('jwt.public_key') . '"',
    'JWT_PUBLIC_KEY="' . str_replace(["\r", "\n"], '||', $key['publickey']) . '"',
    file_get_contents($path)
));

exit;
